[[dynjs-addon]]
DynJS addon
~~~~~~~~~~~

__________________________________________________________________________________________________________________________
Addon that allow to develop a http://forge.jboss.org/addons[forge addon]
using http://dynjs.org/[DynJS javascript engine].
__________________________________________________________________________________________________________________________

[[available-commands]]
Available Commands
^^^^^^^^^^^^^^^^^^

[cols=",<",options="header",]
|=====================================================
|Command |Description
|eval |_Evaluate a script_
|evalinproject |_Evaluate a script in project’s scope_
|installmodule |_Install a new common module_
|=====================================================

[[eval]]
> eval
^^^^^^

_______________________________________________________________________________________________________________________________________________________________________
Evaluate a script #### Parameters | param | Description | | ————-
|:————-| | –script | _script’s full path_ | #### Implicit Object(s)
Object(s) Available in the script
_______________________________________________________________________________________________________________________________________________________________________

[cols=",<",options="header",]
|=======================================================================
|> |object |Description
|self |the current
http://bsorrentino.github.io/forge-addon/dynjs-addon/apidocs/org/bsc/commands/Eval.html[command]
instance
|=======================================================================

[[evalinproject]]
> evalinproject
^^^^^^^^^^^^^^^

__________________________________________________________________________________________________________________________________________________________________________________________
Evaluate a script in project’s scope #### Parameters | param |
Description | | ————- |:————-| | –script | _script’s full path_ | ####
Implicit Object(s) Object(s) Available in the script
__________________________________________________________________________________________________________________________________________________________________________________________

[cols=",<",options="header",]
|=======================================================================
|> |object |Description
|self |the current
http://bsorrentino.github.io/forge-addon/dynjs-addon/apidocs/org/bsc/commands/EvalInProject.html[command]
instance

|project |the current
http://docs.jboss.org/forge/javadoc/2.6.1-SNAPSHOT/org/jboss/forge/addon/projects/Project.html[project]
instance
|=======================================================================

[[installmodule]]
> installmodule
^^^^^^^^^^^^^^^

___________________________________________________________________________________________________________________________________________________________________________________________________________
Install a new common module. After installation such module will be
available to script using *require* command #### Parameters | param |
Description | | ————- |:————-| | –script | _script’s full path_ |
___________________________________________________________________________________________________________________________________________________________________________________________________________

[[getting-started]]
Getting started
^^^^^^^^^^^^^^^

[[install]]
Install
+++++++

`> forge --install org.bsc:dynjs-addon,2.7.2.Final`

_Older versions_

`> forge --install org.bsc:dynjs-addon,2.6.0.Final`

All available version
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.bsc%22%20AND%20a%3A%22dynjs-addon%22[here]

[[javascript-basic-template]]
Javascript basic template
+++++++++++++++++++++++++

code,javascript-----------------------------------------------------------------------
code,javascript
var input = {}; // object containing the UIInput(s)

function initializeUI( builder ) { // Initialize UI & fill input object

  print( "initialize UI");

}

function execute( context ) { // perform task using the input values

  print( "executeJS " );
}
-----------------------------------------------------------------------

[[examples]]
Examples
^^^^^^^^

[[print-the-values-of-required-inputs]]
Print the values of required inputs
+++++++++++++++++++++++++++++++++++

```javascript var String = java.lang.String; var Boolean =
java.lang.Boolean;

print( ``addon loaded!'');

var input = \{};

// initialize an UIInput (String) input.string0 =
self.componentFactory.createInput(``string0'', String );
input.string0.label = ``Give me a string''; input.string0.required =
true;

// initialize an UIInput (Boolean) input.bool0 =
self.componentFactory.createInput(``bool0'', Boolean );
input.bool0.label = ``Give me boolean''; input.bool0.DefaultValue =
true;

function initializeUI( builder ) \{

----------------------------
print( "initialize UI");
for( m in input ) {
    builder.add( input[m] );
}
print( "UI initialized!")
----------------------------

}

function execute( context ) \{

----------------------
print( "executeJS " );

return "
----------------------
